version: '2.2'
services:
  proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
    - 80:80
    depends_on:
    - elastic
    networks:
    - benet

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: be-elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    networks:
    - benet

volumes:
  esdata:
    driver: local

networks:
  benet:
